# Generated by Django 5.0.6 on 2026-04-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('author', models.CharField(max_length=100, verbose_name='著者')),
                ('genre', models.CharField(choices=[('novel', '小説'), ('tech', '技術書'), ('business', 'ビジネス'), ('other', 'その他')], default='other', max_length=20, verbose_name='ジャンル')),
                ('review', models.TextField(blank=True, verbose_name='感想')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '書籍',
                'verbose_name_plural': '書籍一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
